### ISSUE TITLE
Add support for Debian Wheezy

### ISSUE THREAD

**Issue by c-rack** [kkeane/chef-denyhosts#1]
On Debian Wheezy, there is no package `tcp_wrappers` available.
It is also not needed for _denyhosts_ to work properly.
After commenting out package declaration for `tcp_wrappers`, I was able to install _denyhosts_.

Could we make `tcp_wrappers`mandatory for CentOS only?

**Comment by kkeane** [comment]
Thanks for letting me know!

Could you make a pull request, please? That seems to be the github way to do things like this. BTW, on Debian, is tcp_wrappers automatically installed, or does it require some other package name?

Thanks!

Kevin Keane

The NetTech

﻿http://www.4nettech.com

Our values: Privacy, Liberty, Justice

See https://www.4nettech.com/corp/the-nettech-values.html

-----Original message-----

**Comment by c-rack** [comment]
The package is named `tcpd` on Debian:
https://packages.debian.org/wheezy/tcpd

I submitted a PR: https://github.com/kkeane/chef-denyhosts/pull/2
